######################################################################################################
### @Tesla Powerwall - https://www.vcloudinfo.com/2018/01/going-green-to-save-some-green-in-2018.html
# # @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
######################################################################################################

#-------------------------------------------
group:
  Power:
    entities:
      - binary_sensor.grid_status
      - sensor.powerwall_battery_capacity
      - sensor.powerwall_charge
      - sensor.powerwall_charge_now
      - sensor.powerwall_load_now
      - sensor.powerwall_site_now
      - sensor.powerwall_solar_now

#-------------------------------------------

#homeassistant:
#    customize:
#        sensor.powerWall_battery_now:
#            battery_sensor_creation_disabled: true

sensor:
  - platform: integration
    source: sensor.powerwall_solar_now
    name: solar_produced
    round: 2

automation:
  - alias: Notify if Grid is down
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_status

    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ states('binary_sensor.grid_status') == 'on' }}"
        - condition: template
          value_template: "{{ states('binary_sensor.grid_status') == 'off' }}"

    action:
      - service: script.notify_sms_oscar
        data_template:
          message: "The electrical grid is reporting to be {{ (trigger.to_state.state)|replace('on', 'up')|replace('off', 'down') }}.  Please verify with Tesla App."
