- id: pause_all_automations_after_restart
  alias: Pause automations for 15s on restart
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: group.all_automations
    service: automation.turn_off
  - delay: '15'
  - data:
      entity_id: group.all_automations
    service: automation.turn_on
- id: letsencrypt_renewal
  alias: Lets encrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: turn_on_pantry_lights_when_door_opens
  alias: Turn on pantry lights when door opens
  trigger:
  - entity_id: binary_sensor.pantry_door_contact
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.pantry
    service: light.turn_on
- id: turn_off_pantry_lights_when_door_closes
  alias: Turn off pantry lights when door closes
  trigger:
  - entity_id: binary_sensor.pantry_door_contact
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.pantry
    service: light.turn_off
- id: open_garage_door_when_highlander_is_back
  alias: Open garage door when Highlander is back
  trigger:
  - entity_id: binary_sensor.highlander_presence
    for:
      minutes: 5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: cover.garage_door_opener
    service: cover.open_cover
- id: notify_mud_room_door_open
  alias: Notify Mud Room Door Open
  trigger:
  - entity_id: binary_sensor.mud_room_door_contact
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data:
        method: announce
        type: tts
      message: Please close the mud room door.
      target:
      - Kitchen
    service: notify.alexa_media_kitchen
  - delay: 00:00:30
- id: vent_guest_bathroom
  alias: Vent Guest Bathroom
  trigger:
  - entity_id: switch.guest_bathroom_lights
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - delay: 00:00:20
  - data:
      entity_id: light.guest_bathroom_vent
    service: light.turn_off
  - delay: '30'
  - data:
      entity_id: light.guest_bathroom_vent
    service: light.turn_off
- id: turn_on_all_patio_lights_when_switch_is_on
  alias: Turn on all patio lights when switch is on
  trigger:
  - entity_id: light.patio_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.gazibo_gardenspot
    service: light.turn_on
  - data:
      entity_id: switch.gazibo_lights
    service: switch.turn_on
  - data:
      entity_id: light.backyard_light
    service: light.turn_on
- id: turn_off_all_patio_lights_when_switch_is_off
  alias: Turn off all patio lights when switch is off
  trigger:
  - entity_id: light.patio_lights
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.gazibo_gardenspot
    service: light.turn_off
  - data:
      entity_id: switch.gazibo_lights
    service: switch.turn_off
  - data:
      entity_id: light.backyard_light
    service: light.turn_off
- id: turn_off_master_bed_when_lamp_1_is_off
  alias: Turn off master bed when lamp 1 is off
  trigger:
  - entity_id: light.master_bed_lamp_1
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_bed_lamp_2
    state: 'off'
  action:
  - data:
      entity_id: light.master_bed
    service: light.turn_off
- id: turn_off_master_bed_when_lamp_2_is_off
  alias: Turn off master bed when lamp 2 is off
  trigger:
  - entity_id: light.master_bed_lamp_2
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_bed_lamp_1
    state: 'off'
  action:
  - data:
      entity_id: light.master_bed
    service: light.turn_off
- id: Lock_den_when_oscar_leaves
  alias: Lock Den when Oscar leaves
  trigger:
  - entity_id: person.oscar_calvo
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: lock.den
    service: lock.lock
- id: i_am_back
  alias: I am Back
  trigger:
  - entity_id: ' group.person_adults'
    platform: state
    to: home
  condition: []
  action:
  - service: script.i_am_back
- id: goodbye
  alias: Goodbye
  trigger:
  - entity_id: group.person_adults
    for: 00:05:00
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.goodbye
- id: good_night
  alias: Good night
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: disarmed
  - condition: state
    entity_id: group.night_motion_sensors
    for:
      hours: 0
      minutes: 20
      seconds: 0
    state: 'off'
  - condition: state
    entity_id: group.perimeter_contacts
    for:
      hours: 0
      minutes: 20
      seconds: 0
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: script.good_night
- id: good_morning
  alias: Good Morning
  trigger:
  - entity_id: group.sleep_motion_sensors
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_night
  action:
  - service: script.good_morning
  - service: speedtestdotnet.speedtest
- id: close_all_blinds_after_sunset
  alias: Close all blinds after sunset
  trigger:
  - event: sunset
    offset: 00:15:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.all_blinds
    service: cover.close_cover
- id: notify_kid_awake
  alias: Notify Kid awake
  trigger:
  - entity_id: group.kid_doors
    platform: state
    to: 'on'
  condition:
  - after: '20:30:00'
    before: 03:00:00
    condition: time
  action:
  - data:
      message: Kid is awake
      title: Kid is awake
    service: notify.pushover
  - data:
      data:
        method: announce
        type: tts
      message: Kid is awake
      target:
      - media_player.kitchen_echo
      - media_player.master_bedroom_echo
      - media_player.master_bathroom_echo
    service: notify.alexa_media
- id: open_upstairs_blinds
  alias: Open Upstairs Blinds
  trigger:
  - entity_id: binary_sensor.tv_room_motion_sensor_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.stairs_motion_sensor_motion
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    before: sunset
    before_offset: -04:00:00
    condition: sun
  - after: 08:00:00
    condition: time
  - below: '80'
    condition: numeric_state
    entity_id: sensor.treadmill_wattage
  action:
  - data:
      entity_id: cover.tv_room_blinds
    service: cover.open_cover
  - data:
      entity_id: cover.stairs_blinds
    service: cover.open_cover
- id: open_downstairs_blinds
  alias: Open downstairs blinds
  trigger:
  - entity_id: binary_sensor.dinning_motion_sensor_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_motion_sensor_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.kitchen_motion_sensor_motion
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    before: sunset
    before_offset: -04:00:00
    condition: sun
  - after: 08:00:00
    condition: time
  action:
  - data:
      entity_id: cover.living_blinds
    service: cover.open_cover
  - data:
      entity_id: cover.living_left_blinds
    service: cover.open_cover
  - data:
      entity_id: cover.living_right_blinds
    service: cover.open_cover
- id: workout
  alias: Workout
  trigger:
  - above: '80'
    entity_id: sensor.treadmill_wattage
    platform: numeric_state
  condition: []
  action:
  - alias: ''
    data: {}
    service: script.workout
- id: lights_off
  alias: Lights Off
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.house_sleep
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
  - service: script.lights_off
- id: turn_on_living_lights
  alias: Turn on Living Lights
  trigger:
  - entity_id: light.living_lights_switch
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      brightness: '255'
      entity_id: light.living_lights
      white_value: '255'
    service: light.turn_on
- id: turn_off_living_lights
  alias: Turn off Living Lights
  trigger:
  - entity_id: light.living_lights_switch
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.living_lights
    service: light.turn_off
- id: toggle_master_bed_lamp_1_when_button_is_pressed
  alias: Toggle Master Bed Lamp 1 when Button 1 is pressed
  trigger:
  - event_data:
      command: button_single
      device_ieee: 28:6d:97:00:01:03:81:9f
    event_type: zha_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.master_bed_lamp_1
    service: light.toggle
- id: toggle_master_bed_lamp_2_when_button_is_pressed
  alias: Toggle Master Bed Lamp 2 when Button 2 is pressed
  trigger:
  - event_data:
      command: button_single
      device_ieee: 28:6d:97:00:01:03:81:88
    event_type: zha_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.master_bed_lamp_2
    service: light.toggle
- id: turn_on_master_bed_lamps_when_master_lights_turned_on
  alias: Turn on Master Bed Lamps when Master Lights turned on
  trigger:
  - entity_id: light.master_bedroom_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.master_bed_lamp_1
    service: light.turn_on
  - data:
      entity_id: light.master_bed_lamp_2
    service: light.turn_on
- id: turn_on_master_bed_when_master_lamps_turn_on
  alias: Turn on Master Bed when Master Lamps turn on
  trigger:
  - entity_id: light.master_bed_lamp_1
    platform: state
    to: 'on'
  - entity_id: light.master_bed_lamp_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.master_bed
    service: light.turn_on
- id: turn_off_master_bedroom_lights_when_lamps_are_off
  alias: Turn off Master Bedroom Lights when Lamps are off
  trigger:
  - entity_id: light.master_bed_lamp_1
    platform: state
    to: 'off'
  - entity_id: light.master_bed_lamp_2
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom_lights
    service: light.turn_off
- id: reboot_every_sunday
  alias: Reboot every Sunday
  description: ''
  trigger:
  - at: 04:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data:
      message: Reboot
    service: notify.sms_oscar
  - service: hassio.host_reboot
- id: '1582498149789'
  alias: Notify if Internet Connection changes
  description: ''
  trigger:
  - entity_id: binary_sensor.cable_modem
    platform: state
  - entity_id: binary_sensor.lte_modem
    platform: state
  condition: []
  action:
  - data_template:
      message: Public IP has changed to {{ states("sensor.public_ip") }}
    service: notify.sms_oscar
- id: '1582741780213'
  alias: Turn off cable modem switch if cable modem connection is off for more than
    5 minutes
  description: ''
  trigger:
  - entity_id: binary_sensor.cable_modem
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Restarting cable modem, it has been down for more than 5 minutes
    service: notify.sms_oscar
  - entity_id: switch.cable_modem
    service: switch.turn_off
  - delay: '10'
  - entity_id: switch.cable_modem
    service: switch.turn_on
- id: irrigate_home
  alias: Irrigate Home
  description: ''
  trigger:
  - entity_id: sun.sun
    platform: state
    to: above_horizon
  condition: []
  action:
  - data: {}
    entity_id: switch.irrigation_controller_zone_3
    service: script.irrigate_home
- id: '1596227431193'
  alias: Turn on Kitchen Speaker
  description: ''
  trigger:
  - entity_id: media_player.downstairs
    platform: state
    to: playing
  - entity_id: light.kitchen_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    service: script.turn_on_samsung_kitchen_speaker
  mode: single
