- id: pause_all_automations_after_restart
  alias: Pause automations for 15s on restart
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: group.all_automations
    service: automation.turn_off
  - delay: '15'
  - data:
      entity_id: group.all_automations
    service: automation.turn_on
- id: '1560743327162'
  alias: Turn on pantry lights when door opens
  trigger:
  - entity_id: binary_sensor.pantry_door_contact
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.pantry
    service: light.turn_on
- id: '1560824051488'
  alias: Turn off pantry lights when door closes
  trigger:
  - entity_id: binary_sensor.pantry_door_contact
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.pantry
    service: light.turn_off
- id: '1561335344275'
  alias: Highlander is back
  trigger:
  - entity_id: binary_sensor.highlander_presence
    for:
      minutes: 5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: cover.garage_door_opener
    service: cover.open_cover
- id: '1561336574713'
  alias: Notify Mud Room Door Open
  trigger:
  - entity_id: binary_sensor.mud_room_door_contact
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data:
        method: announce
        type: tts
      message: Please close the mud room door.
      target:
      - Kitchen
    service: notify.alexa_media_kitchen
  - delay: 00:00:30
- id: '1561339381492'
  alias: Vent Guest Bathroom
  trigger:
  - entity_id: switch.guest_bathroom_lights
    for: 00:02:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - delay: 00:00:20
  - data:
      entity_id: light.guest_bathroom_vent
    service: light.turn_off
  - delay: '30'
  - data:
      entity_id: light.guest_bathroom_vent
    service: light.turn_off
- id: '1561340212469'
  alias: Turn on all patio lights when switch is on
  trigger:
  - entity_id: switch.patio_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.gazibo_gardenspot
    service: light.turn_on
  - data:
      entity_id: switch.gazibo_lights
    service: switch.turn_on
  - data:
      entity_id: switch.backyard
    service: switch.turn_on
- id: '1561340586010'
  alias: Turn off all patio lights when switch is off
  trigger:
  - entity_id: switch.patio_lights
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.gazibo_gardenspot
    service: light.turn_off
  - data:
      entity_id: switch.gazibo_lights
    service: switch.turn_off
  - data:
      entity_id: switch.backyard
    service: switch.turn_off
- id: '1561414528681'
  alias: Turn off master bed when lamp 1 is off
  trigger:
  - entity_id: light.master_bed_lamp_1
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_bed_lamp_2
    state: 'off'
  action:
  - data:
      entity_id: light.master_bed
    service: light.turn_off
- id: '1561414593093'
  alias: Turn off master bed when lamp 2 is off
  trigger:
  - entity_id: light.master_bed_lamp_2
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_bed_lamp_1
    state: 'off'
  action:
  - data:
      entity_id: light.master_bed
    service: light.turn_off
- id: '1561676291737'
  alias: Lock Den when Oscar leaves
  trigger:
  - entity_id: person.oscar_calvo
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: lock.den
    service: lock.lock
- id: '1561788825399'
  alias: I am Back
  trigger:
  - entity_id: ' group.person_adults'
    platform: state
    to: home
  condition: []
  action:
  - service: script.i_am_back
- id: '1561789045778'
  alias: Goodbye
  trigger:
  - entity_id: group.person_adults
    for: 00:05:00
    platform: state
    to: not_home
  condition: []
  action:
  - service: script.goodbye
- id: '1561790296057'
  alias: Good night
  trigger:
  - entity_id: group.sleep_motion_sensors
    for: 00:30:00
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: disarmed
  - after: sunset
    after_offset: 02:00:00
    condition: sun
  action:
  - service: script.good_night
- id: '1561790815508'
  alias: Good Morning
  trigger:
  - entity_id: group.sleep_motion_sensors
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    condition: sun
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_night
  action:
  - service: script.good_morning
- id: '1561828039799'
  alias: Close all blinds after sunset
  trigger:
  - event: sunset
    offset: 00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.all_blinds
    service: cover.close_cover
