- platform: ping
  host: 1.1.1.1
  count: 3
  scan_interval: 30
  name: Internet
- platform: ping
  host: 192.168.1.101
  count: 3
  scan_interval: 30
  name: Server
- platform: template
  sensors: !include binary_sensors.template.yaml
