- platform: arlo
  ffmpeg_arguments: '-pred 1 -q:v 2'
- platform: ring
- platform: ffmpeg
  name: 'Den'
  input: !secret camera_den_url
- platform: ffmpeg
  name: 'Garage'
  input: !secret camera_garage_url
- platform: ffmpeg
  name: 'TV Room'
  input: !secret camera_tvroom_url
- platform: ffmpeg
  name: 'Living'
  input: !secret camera_living_url
