- platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: liftmaster
- platform: template
  covers:
    bedroom_3_vent:
      friendly_name: "Bedroom 3 Vent"
      position_template: '{{ float(state_attr("light.bedroom_3_vent", "brightness")/ 255 * 100) | round(0) | int | round(0) | int }}'
      set_cover_position:
        service: light.turn_on
        data_template:
          entity_id: light.bedroom_3_vent
          brightness: '{{ float(position * 255 / 100) | round(0) | int }}'
