- platform: edgeos
  #List of network devices to treat as device tracker
  hosts:
    - server
    - Oscar-Phone
    - Hazel-Phone
    - Nexus-Phone
- platform: ping
  scan_interval: 30
  hosts:
    Oscar_Phone: 192.168.1.56
    Hazel_Phone: 192.168.1.54
    Nexus_Phone: 192.168.1.80
- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret
