- platform: html5
  name: notify_html5
  vapid_pub_key: !secret notify_vapid_pub_key
  vapid_prv_key: !secret notify_vapid_prv_key
  vapid_email: !secret notify_vapid_email
- platform: pushover
  name: PushOver
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key
