- platform: html5
  name: notify_html5
  vapid_pub_key: !secret notify_vapid_pub_key
  vapid_prv_key: !secret notify_vapid_prv_key
  vapid_email: !secret notify_vapid_email
- platform: pushover
  name: PushOver
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key
- platform: sms
  name: sms_oscar
  recipient: !secret sms_oscar
- platform: sms
  name: sms_hazel
  recipient: !secret sms_hazel
- platform: group
  name: all
  services:
    - service: pushover
      data_template:
        message: '{{ message }}'
        title: "Broadcast Notification"
        data:
          url: "https://duvall.calvonet.com:8123/"
          sound: pianobar
          priority: 0
          #attachment: "http://example.com/image.png"
    - service: tts_google_translate_say
      data_template:
        entity_id: media_player.kitchen_display
        message: '{{ message }}'
        cache: true
