- platform: group
  name: all
  services:
    - service: pushover
      data_template:
        message: '{{ message }}'
        title: "Broadcast Notification"
        data:
          url: "https://duvall.calvonet.com:8123/"
          sound: pianobar
          priority: 0
          #attachment: "http://example.com/image.png"
    - service: tts_google_translate_say
      data_template:
        entity_id: media_player.kitchen_display
        message: '{{ message }}'
        cache: true
- platform: group
  name: sms_oscar
  services:
    - service: sms
      data:
        target: !secret sms_oscar
- platform: group
  name: sms_hazel
  services:
    - service: sms
      data:
        target: !secret sms_hazel
