- alias: update_vent_group_members
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/30'
      seconds: 00
  action:
    - service: group.set
      data_template:
        object_id: "all_vents"
        entities: >-
          {%- for vent in states['cover'] if ( (vent.entity_id | lower).endswith('_vent') ) -%}
            {{ vent.entity_id }}{% if not loop.last %}, {% endif %}
          {%- endfor -%}
- alias: vent_home
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
  action:
    - service: group.set
      data_template:
        object_id: "closed_vents"
        entities: >-
            {% macro get_name(vent) -%}
            {{- vent.entity_id.replace('_vent','').replace('cover.','') -}}
            {%- endmacro -%}
            {% macro get_room_temp(vent) -%}
            sensor.{{get_name(vent)}}_sensor_air_temperature
            {%- endmacro -%}
            {% macro get_close(vent) -%}
            {% set target = state_attr("climate.smart_climate", "temperature")|float(20) -%}
            {% set hvacMode = state_attr("climate.smart_climate", "hvac_action")|lower -%}
            {% set room = states(get_room_temp(vent))|float(20) -%}
            {% set level = state_attr(vent.entity_id, "current_position") -%}
            {% if level == None -%}{% set level = 50 -%}{% endif -%}
            {% set delta = 0.25 -%}
            {% set roomIsHot = (room - target) > delta -%}
            {% set roomIsCold = (target - room) > delta -%}
            {% set requestClose = (roomIsCold and hvacMode == 'cooling') or (roomIsHot and hvacMode == 'heating') -%}
            {% if requestClose -%}
            {{vent.entity_id}}
            {%- endif -%}
            {%- endmacro -%}
            {% set ns = namespace(results=[]) %}
            {% for vent in states.cover if vent.entity_id.endswith('_vent') %}
              {% set result = get_close(vent) %}
              {% if result %}
                {% set ns.results = ns.results + [result] %}
              {% endif %}
            {% endfor %}
            {{ ns.results | join(',') }}
    - service: cover.set_cover_position
      data_template:
        position: "{{ states('input_number.vent_aperture_min') | int(0) }}"
        entity_id: group.closed_vents
    - service: group.set
      data_template:
        object_id: "open_vents"
        entities: >-
            {% macro get_name(vent) -%}
            {{- vent.entity_id.replace('_vent','').replace('cover.','') -}}
            {%- endmacro -%}
            {% macro get_room_temp(vent) -%}
            sensor.{{get_name(vent)}}_sensor_air_temperature
            {%- endmacro -%}
            {% macro get_open(vent) -%}
            {% set target = state_attr("climate.smart_climate", "temperature")|float(20) -%}
            {% set hvacMode = state_attr("climate.smart_climate", "hvac_action")|lower -%}
            {% set room = states(get_room_temp(vent))|float(20) -%}
            {% set level = state_attr(vent.entity_id, "current_position") -%}
            {% if level == None -%}{% set level = 50 -%}{% endif -%}
            {% set delta = 0.25 -%}
            {% set roomIsHot = (room - target) > delta and (room != 0) -%}
            {% set roomIsCold = (target - room) > delta and (room != 0) -%}
            {% set requestOpen = (roomIsHot and (hvacMode == 'cooling')) or (roomIsCold and hvacMode == 'heating') -%}
            {% if requestOpen -%}
            {{vent.entity_id}}
            {%- endif -%}
            {%- endmacro -%}
            {% set ns = namespace(results=[]) %}
            {% for vent in states.cover if vent.entity_id.endswith('_vent') %}
              {% set result = get_open(vent) %}
              {% if result %}
                {% set ns.results = ns.results + [result] %}
              {% endif %}
            {% endfor %}
            {{ ns.results | join(',') }}
    - service: cover.set_cover_position
      data_template:
        position: "{{ states('input_number.vent_aperture_max') | int(100) }}"
        entity_id: group.open_vents
